name = "tvseriesco"
main = "src/index.ts"
compatibility_date = "2023-05-20"
usage_model = "unbound"
env = { }

[[routes]]
pattern = "*.uploader4tv.ga/*"
zone_name = ""
script = "tvseriesco"

[[routes]]
pattern = "*.u4tv.ga/*"
zone_name = ""
script = "tvseriesco"

[triggers]
crons = [ ]
